### ISSUE TITLE
método search da árvore B com index errado

### ISSUE THREAD

**Issue by viniciusbds** [RichElton/Leda-20182#3]
int index = 1;

		while (index <= node.size() && element.compareTo(node.getElementAt(index)) > 0) {
			index += 1;
		}
		if (index <= node.size() && element == node.getElementAt(index)) {
			return new BNodePosition<T>(node, index);
		}
		if (node.isLeaf()) {
			return new BNodePosition<T>();
		}
		return search(node.getChildren().get(index), element);

O correto n seria começar com index = 0 ?

[link](https://github.com/RichElton/Leda-20182/blob/master/R17-01-Rot-ArvoreB-environment/src/main/java/adt/btree/BTreeImpl.java)

**Comment by RichElton** [comment]
Verdade, vou corrigir.
